### ISSUE TITLE
Crash on gen

### ISSUE THREAD

**Issue by nyurik** [duivvv/generator-module-boilerplate#36]
```
~/dev/osm/osmapi-js$ yo module-boilerplate
? Module Name osmapi-js
? License MIT
? Author (also used in license) Yuri Astrakhan
? Author Email YuriAstrakhan@gmail.com
? Description description123
? Github Username nyuriks
? Do you need Flow for type checking? (No) No
? Are you using Gitmoji in your commits? (No) Yes

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/generators/app/templates/.github/ISSUE_TEMPLATE.md
    at EditionInterface.exports._copySingle (/home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at child._copyFile (/home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/generators/app/index.js:62:13)
    at files.forEach.f (/home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/generators/app/index.js:242:31)
    at Array.forEach (native)
    at child.settings (/home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/generators/app/index.js:242:13)
    at Object.<anonymous> (/home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/node_modules/yeoman-generator/lib/base.js:439:23)
    at /home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/node_modules/run-async/index.js:25:25
    at /home/yurik/.nvm/versions/node/v6.11.3/lib/node_modules/generator-module-boilerplate/node_modules/run-async/index.js:24:19
```

**Comment by duivvv** [comment]
should be fixed now
